// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { neueHaasDisplay } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black scroll-smooth scroll-pt-20">
      <body className={`${neueHaasDisplay.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
